backend:
  name: git-gateway
  branch: main

media_folder: "static/img/uploads"
public_folder: "static/img/uploads"

collections:
  - name: "posts"
    label: "Posts do Blog"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "excerpt", widget: "text" }
      - { label: "Imagem de Destaque", name: "image", widget: "image" }
      - { label: "Corpo do Post", name: "body", widget: "markdown" }
